- name: Disable IPv6
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
  ignore_errors: yes
  retries: 2
  delay: 5
  become: True
  with_items: 
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  async: 45
  poll: 5
  check_mode: no

- name: Ensure vimrc
  template:
    src: vimrc
    dest: /home/headhoncho/.vimrc
    owner: headhoncho
    group: headhoncho
    mode: 0644

- name: Ensure tmux config
  template:
    src: tmux.conf
    dest: /home/headhoncho/.tmux.conf
    owner: headhoncho
    group: headhoncho
    mode: 0644

- name: Check that the cloud.cfg exists
  stat:
    path: /etc/cloud/cloud.cfg
  register: cloud_exists

### Make host name persitent after reboot
- name: Ensure preserve_hostname is set to True
  lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: '^preserve_hostname:'
    line: 'preserve_hostname: true'
  become: true
  when:
    - cloud_exists.stat.exists == true
  
- name: Check that the vars.sh exists
  stat:
    path: /lib/init/vars.sh
  register: vars_exists

- name: Ensure fsck is run non-interactively
  lineinfile:
    path: /lib/init/vars.sh
    regexp: '^FSCKFIX'
    line: 'FSCKFIX=yes'
  become: true
  when:
    - vars_exists.stat.exists == true

- name: Check that the rcS exists
  stat:
    path: /etc/default/rcS
  register: rcS_exists

- name: Fool vcenter 6.5 to belive OS is 18.04 for NIC customization (revert after deployed) 20.04 supported in vcenter 6.7
  lineinfile:
    path: /etc/issue
    regexp: '^Ubuntu'
    line: 'Ubuntu 18.04.4 LTS \n \l'
    backup: yes
  become: true